-- 0008_task_attachments_staging.sql
-- Attach-on-create: let files be uploaded and staged BEFORE a task exists.
--
-- The "New task" popups (dashboard.php, project_view.php) now upload files the
-- moment they are chosen — Anton-chat style, with a live progress bar — long
-- before the task row is inserted. Staged rows carry task_id = NULL until the
-- task is saved, at which point the create handler claims them:
--     UPDATE task_attachments SET task_id = N WHERE id IN (...) AND task_id IS NULL
--
-- Making task_id nullable is safe on both schema variants: the fk_ta_task
-- foreign key (preferred schema) already permits NULL, and the no-FK variant
-- (migration 0003) has no constraint at all.
ALTER TABLE task_attachments MODIFY COLUMN task_id INT NULL;
